import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {AuthProvider} from "@/app/auth";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'static-site-oauth',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <AuthProvider>
              {children}
          </AuthProvider>
      </body>
    </html>
  )
}
